create UTF8 database; add unison-aux to schema list

diff --git a/tools/sbin/dev2stage b/tools/sbin/dev2stage
--- a/tools/sbin/dev2stage
+++ b/tools/sbin/dev2stage
@@ -1,9 +1,9 @@
 #!/bin/sh -e
 # dev2stage: copy dev database to stage
 # usage: dev2stage <stage-name>
-# $Id: dev2stage,v 1.17 2006/09/13 16:10:37 mukhyala Exp $
+# $Id: dev2stage,v 1.18 2006/09/20 21:08:19 mukhyala Exp $
 
-echo '# $Id: dev2stage,v 1.17 2006/09/13 16:10:37 mukhyala Exp $' 1>&2
+echo '# $Id: dev2stage,v 1.18 2006/09/20 21:08:19 mukhyala Exp $' 1>&2
 
 if [ $# != 1 -o -z "$1" ]; then
 	echo "$0: exactly one non-empty argument required for the stage name" 1>&2
@@ -25,32 +25,32 @@ if psql </dev/null >/dev/null 2>/dev/null; then
 fi
 
 # create the new database with necessary languages
-createdb "$PGDATABASE";
+createdb -EUTF8 "$PGDATABASE";
 createlang plpgsql
 createlang plperl
 createlang plperlu
 
 
 # restore selected schemas; order is important
-SCHEMAS="postgres  pgtools public  go gong ncbi pdb scop sst tax marray unison"
+SCHEMAS="postgres  pgtools public  go gong ncbi pdb scop sst tax marray unison-aux unison"
 echo "WARNING: I'm staging these schemas ONLY: $SCHEMAS" 1>&2
 for s in $SCHEMAS; do
-		(echo '\set ON_ERROR_STOP' ;
-		PGOPTIONS="-c statement_timeout=0" pg_dump $DUMP_OPTS -n "$s" "csb-dev") | psql -af-
+	(echo '\set ON_ERROR_STOP' ;
+	PGOPTIONS="-c statement_timeout=0" pg_dump $DUMP_OPTS -n "$s" "csb-dev") | psql -af-
 done
 
+
 psql -qaf- <<EOF
-alter database "$PGDATABASE" set search_path = unison,gong,pdb,scop,sst,tax,marray;
-EOF
-#Don't merge these two, analyze needs search path set above.
-psql -qaf- <<EOF
+alter database "$PGDATABASE" set search_path = unison,"unison-aux",gong,pdb,scop,sst,tax,marray;
+
+-- reconnect to enact search_path for analyze
+\c -
+
 analyze verbose;
+
+select meta_update_kv('staged at', '`date +"%Y-%m-%d %H:%M:%S"`');
+select meta_update_kv('staged by', '\$Id: dev2stage,v 1.18 2006/09/20 21:08:19 mukhyala Exp $')
 EOF
 
-# new connection need to use new search_path
-psql -qaf- <<EOF
-select meta_update_kv('staged at', '`date +"%Y-%m-%d %H:%M:%S"`');
-select meta_update_kv('staged by', '\$Id: dev2stage,v 1.17 2006/09/13 16:10:37 mukhyala Exp $')
-EOF
 
 echo `date +'%Y-%m-%d %H:%M:%S'`: $0 done
