utils forcibly redirects all output to logs w/changes to nightly & utils; nightly checks for password

diff --git a/tools/sbin/utils b/tools/sbin/utils
--- a/tools/sbin/utils
+++ b/tools/sbin/utils
@@ -1,19 +1,36 @@
 # -*- sh -*-
-# $Id: utils,v 1.3 2003/07/31 22:42:23 rkh Exp $
+# $Id: utils,v 1.4 2003/09/29 15:28:20 rkh Exp $
 # utils -- misc defaults and utilities for csb-db shell scripts
 
 LOGDIR="/services/logs"
 JEMAPPELLE=`basename $0`
 LOGFN="$LOGDIR/$JEMAPPELLE"
 
-source /apps/compbio/setup.sh
+
+# redirect all output (stdout + stderr)
+exec >>"$LOGDIR/$JEMAPPELLE" 2>&1
+
 
 # logger -- format a log line
 # logger <message>
 logger () { 
 	DATE=`date +"%Y/%m/%d %H:%M:%S"`
-	echo "$DATE $JEMAPPELLE[$$]" "$@" >>"$LOGFN"
-	if [ -t 0 ]; then
-		echo "$DATE $JEMAPPELLE[$$]" "$@" 1>&2
-	fi
-	}
+	echo "$DATE $JEMAPPELLE[$$]" "$@"
+	#if [ -t 0 ]; then
+	#	echo "$DATE $JEMAPPELLE[$$]" "$@"
+	#fi
+}
+
+
+# die -- log (as with logger), then exit
+die () {
+	logger "! ERROR:"
+	logger "!  $@";
+	exit 1;
+}
+
+
+dothis () {
+	logger "cmd: $@"
+	eval "$@"
+}
